# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Info_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(686, 806)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.el_name_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.el_name_label.setFont(font)
        self.el_name_label.setStyleSheet("color: rgb(0, 255, 255);")
        self.el_name_label.setObjectName("el_name_label")
        self.verticalLayout.addWidget(self.el_name_label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.info = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setStyleSheet("color: rgb(0, 255, 255);")
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.physics = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.physics.setFont(font)
        self.physics.setStyleSheet("color: rgb(0, 255, 255);")
        self.physics.setObjectName("physics")
        self.verticalLayout.addWidget(self.physics)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.chemistry = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chemistry.setFont(font)
        self.chemistry.setStyleSheet("color: rgb(0, 255, 255);")
        self.chemistry.setObjectName("chemistry")
        self.verticalLayout.addWidget(self.chemistry)
        self.add_info = QtWidgets.QPushButton(Form)
        self.add_info.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(75, 75, 75);\n"
"")
        self.add_info.setObjectName("add_info")
        self.verticalLayout.addWidget(self.add_info)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.el_name_label.setText(_translate("Form", "Название элемента"))
        self.label_2.setText(_translate("Form", "Основная информация"))
        self.info.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Form", "Физические свойства"))
        self.physics.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Form", "Химические свойства"))
        self.chemistry.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.add_info.setText(_translate("Form", "Дополнительная информация"))
