# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Theme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Theme_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(731, 523)
        Form.setMinimumSize(QtCore.QSize(731, 523))
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.theme_info = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theme_info.setFont(font)
        self.theme_info.setStyleSheet("color: rgb(0, 255, 255);")
        self.theme_info.setObjectName("theme_info")
        self.verticalLayout.addWidget(self.theme_info)
        self.pictures = QtWidgets.QLabel(Form)
        self.pictures.setObjectName("pictures")
        self.verticalLayout.addWidget(self.pictures)
        self.back = QtWidgets.QPushButton(Form)
        self.back.setMinimumSize(QtCore.QSize(75, 23))
        self.back.setMaximumSize(QtCore.QSize(75, 23))
        self.back.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(75, 75, 75);\n"
"")
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Тема"))
        self.pictures.setText(_translate("Form", "TextLabel"))
        self.back.setText(_translate("Form", "Назад"))
